### ISSUE TITLE
How to get the seed.mat from GT

### ISSUE THREAD

**Issue by raytrun** [onvungocminh/MBD_BAL#2]
Hi. Thanks for sharing your nice work. As a beginner, I don't know how to get the seed from GT. May you kindly share some code or related documents. Thank.

**Comment by onvungocminh** [comment]
These seeds are the points that have the maximum Euclidean distance value w.r.t the boundary of each connected component. For more information, you can find in our paper: https://hal.archives-ouvertes.fr/hal-03417244/document. Hope it helps.

**Comment by raytrun** [comment]
Thank you for your reply. I've read your paper and the code of this repo, and I find that the point value seems to include neighbors information with other boundary. It would be very appreciated if you could share more code.

**Comment by rose-jinyang** [comment]
Hi @onvungocminh and @raytrun 
Could u share the code for getting seed?
Thanks

**Comment by rose-jinyang** [comment]
Hi @raytrun
Can we interchange some experiences in using this loss each other?

**Comment by raytrun** [comment]
Hi @rose-jinyang  
Sorry for the late reply. Unfortunately, I'm not working on this code anymore.

**Comment by Dawn-bin** [comment]
> Hi @raytrun Can we interchange some experiences in using this loss each other?

hi, does this work worth to following?

**Comment by onvungocminh** [comment]
We are preparing for a new version of the BALoss, we will public it soon
