### ISSUE TITLE
Can the contours from MBD-cut be replaced by those from GT?

### ISSUE THREAD

**Issue by raytrun** [onvungocminh/MBD_BAL#3]
The loss is calculated depending on the contour from the algorithm of MBD-cut. What will happen if contours are from GT?

**Comment by onvungocminh** [comment]
Hi. If the contours from MBD-cut are replaced by those from the GT, the loss will be similar to the normal binary cross entropy loss , which does not have topology information on the contours.

**Comment by raytrun** [comment]
OK, thanks.
